name: Artefact Builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      run: echo "::set-env name=ARTVERSION::$(grep '"version"' ./src/manifest.json  | cut -d'"' -f4)"
      with:
        name: ${{ env.ARTVERSION }}
        path: ./src/
